name: Build and deploy ASP.Net Core app to Azure Web App - xmla-semanticmodel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Point directly to your .csproj file here:
      - name: dotnet publish
        run: dotnet publish ./TabularModelDeployer.csproj -c Release -o ./myapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'xmla-semanticmodel'
          slot-name: 'Production'
          package: ./myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_47E12A2117864E0EA09F4B0A28A0140C }}
